services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn run start:dev auth
    ports:
      - '3001:3000'
    depends_on:
      - mongodb
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development

    command: yarn run start:dev users
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - '3002:3000'

  reactions:
    build:
      context: .
      dockerfile: ./apps/reactions/Dockerfile
      target: development
    command: yarn run start:dev reactions
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - '3003:3000'

  posts:
    build:
      context: .
      dockerfile: ./apps/posts/Dockerfile
      target: development
    command: yarn run start:dev posts
    depends_on:
      - mongodb
      - rabbitmq
    ports:
        - '3004:3000'

  files:
    build:
      context: .
      dockerfile: ./apps/files/Dockerfile
      target: development
    command: yarn run start:dev files
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - '3005:3000'

  weather:
    build:
      context: .
      dockerfile: ./apps/weather/Dockerfile
      target: development
    command: yarn run start:dev weather
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - '3006:3000'

  reels:
    build:
      context: .
      dockerfile: ./apps/reels/Dockerfile
      target: development
    command: yarn run start:dev reels
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - '3000:3000'

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'

  mongodb:
    container_name: mongodb
    image: mongo:5.0.6
    ports:
      - 27018:27017
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password123
        MONGO_INITDB_DATABASE: isproject


volumes:
  mongodb_master_data:
    driver: local